In [1]:
from google.colab import files
uploaded = files.upload()

Saving amazon.csv to amazon.csv

In [2]:
import pandas as pd

df = pd.read_csv("amazon.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [3]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

np.int64(0)

1. product_id must be unique
2. price must be > 0
3. rating must be between 0–5
4. product_name must not be NULL
5. no duplicate rows

In [5]:
import pandas as pd

# price clean: ₹ and comma remove
df['discounted_price_num'] = (
    df['discounted_price'].astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['actual_price_num'] = (
    df['actual_price'].astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['discounted_price_num'] = pd.to_numeric(df['discounted_price_num'], errors='coerce')
df['actual_price_num'] = pd.to_numeric(df['actual_price_num'], errors='coerce')

# rating clean
df['rating_num'] = pd.to_numeric(df['rating'], errors='coerce')

# rating_count clean
df['rating_count_num'] = (
    df['rating_count'].astype(str)
    .str.replace(',', '', regex=False)
)
df['rating_count_num'] = pd.to_numeric(df['rating_count_num'], errors='coerce')

df[['discounted_price','discounted_price_num','actual_price','actual_price_num','rating','rating_num','rating_count','rating_count_num']].head()

,discounted_price,discounted_price_num,actual_price,actual_price_num,rating,rating_num,rating_count,rating_count_num
0,₹399,399.0,"₹1,099",1099.0,4.2,4.2,"24,269",24269.0
1,₹199,199.0,₹349,349.0,4.0,4.0,"43,994",43994.0
2,₹199,199.0,"₹1,899",1899.0,3.9,3.9,"7,928",7928.0
3,₹329,329.0,₹699,699.0,4.2,4.2,"94,363",94363.0
4,₹154,154.0,₹399,399.0,4.2,4.2,"16,905",16905.0

In [6]:
def validate(df):
    errors = []

    if df.duplicated().sum() > 0:
        errors.append("❌ Duplicate rows found")

    if df['product_id'].duplicated().sum() > 0:
        errors.append("❌ Duplicate product_id found")

    if df['product_name'].isnull().sum() > 0:
        errors.append("❌ product_name has null values")

    if not (df['discounted_price_num'] > 0).all():
        errors.append("❌ discounted_price has invalid values")

    if not (df['actual_price_num'] > 0).all():
        errors.append("❌ actual_price has invalid values")

    if not ((df['rating_num'] >= 0) & (df['rating_num'] <= 5)).all():
        errors.append("❌ rating out of range")

    if not (df['rating_count_num'] >= 0).all():
        errors.append("❌ rating_count invalid")

    if not (df['discounted_price_num'] <= df['actual_price_num']).all():
        errors.append("❌ discounted_price greater than actual_price")

    return errors

issues = validate(df)

if issues:
    print("Data Issues:")
    for i in issues:
        print(i)
else:
    print("✅ Data Clean")

Data Issues:
❌ Duplicate product_id found
❌ rating out of range
❌ rating_count invalid

In [7]:
df[df['product_id'].duplicated()]

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,discounted_price_num,actual_price_num,rating_num,rating_count_num
369,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,270",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/I/51UsScvHQN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,399.0,1099.0,4.2,24270.0
377,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,993","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...,199.0,349.0,4.0,43993.0
379,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,80%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/I/31IvNJZnmd...,https://www.amazon.in/Sounce-iPhone-Charging-C...,199.0,999.0,3.9,7928.0
392,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,364",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,329.0,699.0,4.2,94364.0
393,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/I/31VzNhhqif...,https://www.amazon.in/Portronics-Konnect-POR-1...,154.0,399.0,4.2,16905.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,B0B9BXKBC7,"WeCool S5 Long Selfie Stick, with Large Reinfo...",Electronics|Mobiles&Accessories|MobileAccessor...,"₹1,799","₹3,999",55%,4.6,245,"64"" Tall Cell Phone Tripods with 7 section adj...","AFPYH3UF3GB4RNX3MX46AXFM2FTQ,AGWEQHJSUA4YCG44R...","Sujili v,Paras Jain,Shailendra,supreeth achar,...","R2MI4KSWYUEMDR,R2MNYKDL2UII1M,R2C6TUBM6IVLB0,R...","Good,Good Product but Little expensive.,Happy ...","Good,Thoda sa kam stable hai, phone lagane ke ...",https://m.media-amazon.com/images/I/41fDM4QUfv...,https://www.amazon.in/WeCool-Reinforced-Functi...,1799.0,3999.0,4.6,245.0
1010,B07GVGTSLN,Wayona Usb Type C Fast Charger Cable Fast Char...,Computers&Accessories|Accessories&Peripherals|...,₹325,"₹1,299",75%,4.2,"10,576",Fast Charge & Data Sync: Fast charge& data tra...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/I/41J6oGU8w5...,https://www.amazon.in/Wayona-Cable-Braided-Cha...,325.0,1299.0,4.2,10576.0
1017,B0B9BD2YL4,KINGONE Wireless Charging Pencil (2nd Generati...,Electronics|Mobiles&Accessories|MobileAccessor...,"₹2,599","₹6,999",63%,4.5,"1,526",【2022 latest iPad Magnetic Charging】 The lates...,"AEAX7BRPDS3NSYCZQBQDL5DGZDVA,AFI76LT4UP2L3SFJM...","Ak,Jitesh,anil,Umpo,G'DAS ENTERPRISES,Neetu,Va...","R1HOV97NOJFX4W,R3BIRU7WH404ND,RAU26U2KP1OQH,R1...","Quite Good,good pencil,Value for money,Brillia...",After 10 days of use bhaut acha chl rha ha and...,https://m.media-amazon.com/images/I/217Lv1D3bH...,https://www.amazon.in/Wireless-Generation-Sens...,2599.0,6999.0,4.5,1526.0
1018,B0BMXMLSMM,Lapster 65W compatible for OnePlus Dash Warp C...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,80%,4.5,127,-1 meter type c to c cable fast charging cable...,"AHFENRYJG4LPXDTUGEMG335VICSQ,AGSV37DJ5QTUYOXFJ...","Nadhiyarasan,Saurabh Aggarwal,Dibya,Sai Sriya,...","R14ZOPYFHOYYRQ,R1GQH74NUCJZZ7,R1BNWIYBRSI1Z6,R...","Super charger in lapster,Best among the rest,C...","Best quality,The product looks original-like a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lapster-compatible-OnePl...,199.0,999.0,4.5,127.0
1019,B0141EZMAI,"Gizga Essentials USB WiFi Adapter for PC, 150 ...",Computers&Accessories|NetworkingDevices|Networ...,₹269,₹800,66%,3.6,"10,134",USB WiFi Adapter: Fast wireless transmission a...,"AGMJ6TDLOVZIR5ZU65TLJFSLG2BQ,AGPK7U5SHXBYBXEWB...","SQL,ARUN KUMAR,veer,Ravi shankar,Shivam Kumar,...","R3AZDEK3MQA3RA,RXF3HCCBWV0VB,R6CVYFDUXBS36,R1Q...","Will not work with new system,Veri good,Ok pro...",Was working fine with window 10 old computer b...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Receiver-300Mbps-802-11b...,269.0,800.0,3.6,10134.0

In [8]:
df[(df['rating_num'] < 0) | (df['rating_num'] > 5)]

Empty DataFrame
Columns: [product_id, product_name, category, discounted_price, actual_price, discount_percentage, rating, rating_count, about_product, user_id, user_name, review_id, review_title, review_content, img_link, product_link, discounted_price_num, actual_price_num, rating_num, rating_count_num]
Index: []

In [9]:
df = df.drop_duplicates(subset=['product_id'])

In [10]:
df = df[(df['rating_num'] >= 0) & (df['rating_num'] <= 5)]

In [12]:
df = df.drop_duplicates(subset=['product_id'], keep='first')

In [13]:
df = df[df['rating_num'].notnull()]

In [15]:
df['rating_count_num'] = (
    df['rating_count'].astype(str)
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+)')   # <-- r এখানে লাগবে
)

df['rating_count_num'] = pd.to_numeric(df['rating_count_num'], errors='coerce')

In [16]:
# 1) rating numeric clean first (if not already done)
df = df[df['rating_num'].notnull()]
df = df[(df['rating_num'] >= 0) & (df['rating_num'] <= 5)]

# 2) rating_count clean
df['rating_count_num'] = (
    df['rating_count'].astype(str)
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+)')
)
df['rating_count_num'] = pd.to_numeric(df['rating_count_num'], errors='coerce')
df = df[df['rating_count_num'].notnull()]

# 3) duplicates (ONLY once)
df = df.drop_duplicates(subset=['product_id'], keep='first')

In [17]:
issues = validate(df)

if issues:
    print("Data Issues:")
    for i in issues:
        print(i)
else:
    print("✅ Data Clean")

✅ Data Clean

In [18]:
df.to_csv("clean_amazon.csv", index=False)

from google.colab import files
files.download("clean_amazon.csv")

Project Summary:
Performed Data Quality Testing on Amazon dataset using pandas.
Created validation rules for product_id uniqueness, price validity, rating range,
rating_count validity, and duplicate records.
Detected data quality issues, cleaned invalid records, and validated final clean dataset.